apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-deploy
  labels:
    purpose: autoscale
    env: prod
    kind: deployment
spec:
  replicas: 3
  selector:
# Replicaset uses below labels to find matching pod to create desired no.of pods  
    matchLabels:
      purpose: autoscale
      env: prod
      kind: deployment
# Below is pod template meaning the details of how the pod should be created      
  template:
    metadata:
      labels:
        purpose: autoscale
        env: prod
        kind: deployment
    spec:
      containers:
      - name: nginx
        image: lakshmikanth333/nginx:2.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: LoadBalancer
  selector:
    purpose: autoscale
    env: prod
    kind: deployment
  ports:
  - protocol: TCP  
    port: 80
    targetPort: 80  
    nodePort: 30123

    
